/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.rodrigozago.mongomipster.ui;

import com.rodrigozago.mongomipster.core.Caixa;
import com.rodrigozago.mongomipster.core.Cliente;
import com.rodrigozago.mongomipster.core.Comanda;
import com.rodrigozago.mongomipster.core.Model;
import com.rodrigozago.mongomipster.core.Produto;
import com.rodrigozago.mongomipster.core.Verificador;
import com.rodrigozago.mongomipster.exceptions.CaixaAbertoException;
import com.rodrigozago.mongomipster.exceptions.CaixaFechadoException;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.bson.Document;

/**
 *
 * @author rodrigozago
 */
public class ViewController extends javax.swing.JFrame {
    
   private Caixa caixa;
   private Model database;
   private DefaultTableModel modelProdutosDaComanda;
   private DefaultTableModel modelServicoProdutosDaComanda;
   private DefaultTableModel modelProdutos;
   private Double totalDaComanda;

    /**
     * Creates new form MainWindow
     */
    public ViewController() {
        initComponents();
        initMipster();
    }
    
    private void initMipster()
    {
        this.database = new Model();
        this.caixa = new Caixa(database.getFirstDocument("caixa"));
        
        this.jTextFieldCaixaEstado.setText(this.caixa.caixaAberto()? "ABERTO" : "FECHADO");
        this.jTextFieldCaixaComandasAbertas.setText(String.valueOf(database.getNumComandas()));
        if(this.caixa.caixaAberto())
            this.jTextFieldCaixaIdComanda.setEnabled(true);
        
        this.modelProdutosDaComanda = (DefaultTableModel) this.jTableCaixaComanda.getModel();
        this.modelServicoProdutosDaComanda = (DefaultTableModel) this.jTableServicoProdutosDaComanda.getModel();
        this.modelProdutos = (DefaultTableModel) this.jTableServicoProdutos.getModel();
        
        this.populaJTableProdutos();
    }
    
    private void populaJTableProdutos()
    {
        this.modelProdutos.setRowCount(0);
        ArrayList<Produto> produtos = this.database.getAllProdutos();
        for(Iterator<Produto> i = produtos.iterator(); i.hasNext();)
        {
            Produto pro = i.next();
            Object[] row = {pro.getId(), pro.getNome(), "R$: " + pro.getPreco()};
            this.modelProdutos.addRow(row);
        }
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        mainPanel = new javax.swing.JTabbedPane();
        jPanelCaixa = new javax.swing.JPanel();
        jSeparatorCaixaCabeçalho = new javax.swing.JSeparator();
        jLabelCaixaEstado = new javax.swing.JLabel();
        jTextFieldCaixaEstado = new javax.swing.JTextField();
        jTextFieldCaixaComandasAbertas = new javax.swing.JTextField();
        jLabelCaixaComandasAbertas = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCaixaComanda = new javax.swing.JTable();
        jLabelCaixaCliente = new javax.swing.JLabel();
        jLabelCaixaCPF = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCaixaViewTotalComanda = new javax.swing.JTextField();
        jButtonCaixaFecharComanda = new javax.swing.JButton();
        jTextFieldCaixaViewNomeCliente = new javax.swing.JTextField();
        jTextFieldCaixaViewClienteCPF = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCaixaIdComanda = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldCaixaCPFDoCliente = new javax.swing.JTextField();
        jButtonCaixaAbrirComanda = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanelServico = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableServicoProdutosDaComanda = new javax.swing.JTable();
        jLabelCaixaCliente1 = new javax.swing.JLabel();
        jLabelCaixaCPF1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldServicoViewTotalComanda = new javax.swing.JTextField();
        jTextFieldServicoViewNomeCliente = new javax.swing.JTextField();
        jTextFieldServicoViewClienteCPF = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextFieldServicoIdDaComanda = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableServicoProdutos = new javax.swing.JTable();
        jButtonInserirNaComanda = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jPanelGerenciar = new javax.swing.JPanel();
        jTabbedPaneGerenciar = new javax.swing.JTabbedPane();
        jPanelGerenciarClientes = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldGerenciarClientesCPF = new javax.swing.JTextField();
        jTextFieldGerenciarClientesNome = new javax.swing.JTextField();
        jTextFieldGerenciarClientesSobrenome = new javax.swing.JTextField();
        jTextFieldGerenciarClientesEndereco = new javax.swing.JTextField();
        jTextFieldGerenciarClientesNascimento = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter data= new javax.swing.text.MaskFormatter("##/##/##");
            jTextFieldGerenciarClientesNascimento = new javax.swing.JFormattedTextField(data);
        }
        catch (Exception e){
        }
        jTextFieldGerenciarClientesTelefone = new javax.swing.JTextField();
        try{
            javax.swing.text.MaskFormatter telefone= new javax.swing.text.MaskFormatter("(##) # ####-####");
            jTextFieldGerenciarClientesTelefone = new javax.swing.JFormattedTextField(telefone);
        }
        catch (Exception e){
        }
        jButtonGerenciarClientesAddCliente = new javax.swing.JButton();
        jButtonGerenciarClientesExcluirCliente = new javax.swing.JButton();
        jButtonGerenciarClientesAtualizarCliente = new javax.swing.JButton();
        jPanelGerenciarProdutos = new javax.swing.JPanel();
        jButtonGerenciarProdutosExcluirProduto = new javax.swing.JButton();
        jButtonGerenciarProdutosAdicionarProduto = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGerenciarProdutosPrecoDeCusto = new javax.swing.JTextField();
        jTextFieldGerenciarProdutosPreco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldGerenciarProdutosDescricao = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldGerenciarProdutosNome = new javax.swing.JTextField();
        jTextFieldGerenciarProdutosID = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldGerenciarProdutosQuantEmEstoque = new javax.swing.JTextField();
        jButtonGerenciarProdutosAtualizarProduto = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuAbrirCaixa = new javax.swing.JMenuItem();
        jMenuFecharCaixa = new javax.swing.JMenuItem();

        jTextField1.setText("jTextField1");

        jScrollPane4.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelCaixaEstado.setText("Estado:");

        jTextFieldCaixaEstado.setEditable(false);
        jTextFieldCaixaEstado.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jTextFieldCaixaComandasAbertas.setEditable(false);
        jTextFieldCaixaComandasAbertas.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabelCaixaComandasAbertas.setText("Comandas abertas:");

        jTableCaixaComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCaixaComanda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableCaixaComanda);

        jLabelCaixaCliente.setText("Cliente:");

        jLabelCaixaCPF.setText("CPF:");

        jLabel3.setText("Total:");

        jTextFieldCaixaViewTotalComanda.setEditable(false);

        jButtonCaixaFecharComanda.setText("Fechar comanda");
        jButtonCaixaFecharComanda.setEnabled(false);
        jButtonCaixaFecharComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaFecharComandaActionPerformed(evt);
            }
        });

        jTextFieldCaixaViewNomeCliente.setEditable(false);

        jTextFieldCaixaViewClienteCPF.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCaixaCliente)
                    .addComponent(jLabelCaixaCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCaixaViewNomeCliente)
                    .addComponent(jTextFieldCaixaViewClienteCPF))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 89, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCaixaViewTotalComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonCaixaFecharComanda, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCaixaCliente)
                    .addComponent(jTextFieldCaixaViewNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCaixaCPF)
                    .addComponent(jTextFieldCaixaViewClienteCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCaixaViewTotalComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonCaixaFecharComanda))
        );

        jLabel4.setText("ID da comanda:");

        jTextFieldCaixaIdComanda.setEnabled(false);
        jTextFieldCaixaIdComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCaixaIdComandaActionPerformed(evt);
            }
        });
        jTextFieldCaixaIdComanda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCaixaIdComandaKeyReleased(evt);
            }
        });

        jLabel5.setText("CPF do cliente:");

        jTextFieldCaixaCPFDoCliente.setEnabled(false);
        jTextFieldCaixaCPFDoCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldCaixaCPFDoClienteKeyReleased(evt);
            }
        });

        jButtonCaixaAbrirComanda.setText("Abrir comanda");
        jButtonCaixaAbrirComanda.setEnabled(false);
        jButtonCaixaAbrirComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCaixaAbrirComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 88, Short.MAX_VALUE)
                        .addComponent(jButtonCaixaAbrirComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextFieldCaixaIdComanda)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextFieldCaixaCPFDoCliente)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCaixaIdComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCaixaCPFDoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonCaixaAbrirComanda)
                .addContainerGap(183, Short.MAX_VALUE))
        );

        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelCaixaLayout = new javax.swing.GroupLayout(jPanelCaixa);
        jPanelCaixa.setLayout(jPanelCaixaLayout);
        jPanelCaixaLayout.setHorizontalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparatorCaixaCabeçalho)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelCaixaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelCaixaLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanelCaixaLayout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabelCaixaEstado)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldCaixaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelCaixaComandasAbertas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCaixaComandasAbertas, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanelCaixaLayout.setVerticalGroup(
            jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCaixaLayout.createSequentialGroup()
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCaixaEstado)
                    .addComponent(jLabelCaixaComandasAbertas)
                    .addComponent(jTextFieldCaixaComandasAbertas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCaixaEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparatorCaixaCabeçalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCaixaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.addTab("Caixa", jPanelCaixa);

        jTableServicoProdutosDaComanda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServicoProdutosDaComanda.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTableServicoProdutosDaComanda);

        jLabelCaixaCliente1.setText("Cliente:");

        jLabelCaixaCPF1.setText("CPF:");

        jLabel6.setText("Total:");

        jTextFieldServicoViewTotalComanda.setEditable(false);

        jTextFieldServicoViewNomeCliente.setEditable(false);

        jTextFieldServicoViewClienteCPF.setEditable(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelCaixaCliente1)
                    .addComponent(jLabelCaixaCPF1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldServicoViewNomeCliente)
                    .addComponent(jTextFieldServicoViewClienteCPF))
                .addGap(6, 6, 6))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 128, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldServicoViewTotalComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCaixaCliente1)
                    .addComponent(jTextFieldServicoViewNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCaixaCPF1)
                    .addComponent(jTextFieldServicoViewClienteCPF))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldServicoViewTotalComanda)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jLabel1.setText("ID da comanda:");

        jTextFieldServicoIdDaComanda.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldServicoIdDaComandaKeyReleased(evt);
            }
        });

        jTableServicoProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Produto", "Preço"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServicoProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jTableServicoProdutos);
        if (jTableServicoProdutos.getColumnModel().getColumnCount() > 0) {
            jTableServicoProdutos.getColumnModel().getColumn(1).setResizable(false);
        }

        jButtonInserirNaComanda.setText("Inserir produto na comanda");
        jButtonInserirNaComanda.setEnabled(false);
        jButtonInserirNaComanda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInserirNaComandaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldServicoIdDaComanda)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jButtonInserirNaComanda, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldServicoIdDaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonInserirNaComanda, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(200, 200, 200), 1, true));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelServicoLayout = new javax.swing.GroupLayout(jPanelServico);
        jPanelServico.setLayout(jPanelServicoLayout);
        jPanelServicoLayout.setHorizontalGroup(
            jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelServicoLayout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelServicoLayout.setVerticalGroup(
            jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelServicoLayout.createSequentialGroup()
                .addGroup(jPanelServicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelServicoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        mainPanel.addTab("Servico", jPanelServico);

        jLabel2.setText("CPF:");

        jLabel7.setText("Nome");

        jLabel8.setText("Sobrenome:");

        jLabel9.setText("Endereço:");

        jLabel10.setText("Nascimento:");

        jLabel11.setText("Telefone:");

        jTextFieldGerenciarClientesCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldGerenciarClientesCPFKeyReleased(evt);
            }
        });

        jTextFieldGerenciarClientesNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGerenciarClientesNascimentoActionPerformed(evt);
            }
        });

        jButtonGerenciarClientesAddCliente.setText("Adicionar cliente");
        jButtonGerenciarClientesAddCliente.setEnabled(false);
        jButtonGerenciarClientesAddCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarClientesAddClienteActionPerformed(evt);
            }
        });

        jButtonGerenciarClientesExcluirCliente.setText("Excluir Cliente");
        jButtonGerenciarClientesExcluirCliente.setEnabled(false);
        jButtonGerenciarClientesExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarClientesExcluirClienteActionPerformed(evt);
            }
        });

        jButtonGerenciarClientesAtualizarCliente.setText("Atualizar cliente");
        jButtonGerenciarClientesAtualizarCliente.setEnabled(false);
        jButtonGerenciarClientesAtualizarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarClientesAtualizarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGerenciarClientesLayout = new javax.swing.GroupLayout(jPanelGerenciarClientes);
        jPanelGerenciarClientes.setLayout(jPanelGerenciarClientesLayout);
        jPanelGerenciarClientesLayout.setHorizontalGroup(
            jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                        .addComponent(jButtonGerenciarClientesAddCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerenciarClientesAtualizarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerenciarClientesExcluirCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE))
                    .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(139, 139, 139)
                                .addComponent(jTextFieldGerenciarClientesCPF))
                            .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(104, 104, 104)
                                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGerenciarClientesNome)
                                    .addComponent(jTextFieldGerenciarClientesSobrenome)
                                    .addComponent(jTextFieldGerenciarClientesEndereco)
                                    .addComponent(jTextFieldGerenciarClientesNascimento)
                                    .addComponent(jTextFieldGerenciarClientesTelefone))))))
                .addContainerGap())
        );
        jPanelGerenciarClientesLayout.setVerticalGroup(
            jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarClientesLayout.createSequentialGroup()
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldGerenciarClientesCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldGerenciarClientesNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldGerenciarClientesSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextFieldGerenciarClientesEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldGerenciarClientesNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldGerenciarClientesTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonGerenciarClientesAddCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerenciarClientesAtualizarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonGerenciarClientesExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPaneGerenciar.addTab("Clientes", jPanelGerenciarClientes);

        jButtonGerenciarProdutosExcluirProduto.setText("Excluir produto");
        jButtonGerenciarProdutosExcluirProduto.setEnabled(false);
        jButtonGerenciarProdutosExcluirProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarProdutosExcluirProdutoActionPerformed(evt);
            }
        });

        jButtonGerenciarProdutosAdicionarProduto.setText("Adicionar produto");
        jButtonGerenciarProdutosAdicionarProduto.setEnabled(false);
        jButtonGerenciarProdutosAdicionarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarProdutosAdicionarProdutoActionPerformed(evt);
            }
        });

        jLabel12.setText("Preço de custo:");

        jLabel13.setText("Preço :");

        jLabel15.setText("Descrição:");

        jLabel16.setText("Nome:");

        jTextFieldGerenciarProdutosID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldGerenciarProdutosIDKeyReleased(evt);
            }
        });

        jLabel17.setText("ID:");

        jLabel14.setText("Quantidade em estoque:");

        jButtonGerenciarProdutosAtualizarProduto.setText("Atualizar produto");
        jButtonGerenciarProdutosAtualizarProduto.setEnabled(false);
        jButtonGerenciarProdutosAtualizarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerenciarProdutosAtualizarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelGerenciarProdutosLayout = new javax.swing.GroupLayout(jPanelGerenciarProdutos);
        jPanelGerenciarProdutos.setLayout(jPanelGerenciarProdutosLayout);
        jPanelGerenciarProdutosLayout.setHorizontalGroup(
            jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                        .addComponent(jButtonGerenciarProdutosAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerenciarProdutosAtualizarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonGerenciarProdutosExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                    .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(139, 139, 139)
                                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldGerenciarProdutosID)
                                    .addComponent(jTextFieldGerenciarProdutosNome)))
                            .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel14))
                                .addGap(11, 11, 11)
                                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelGerenciarProdutosLayout.createSequentialGroup()
                                        .addGap(19, 19, 19)
                                        .addComponent(jTextFieldGerenciarProdutosQuantEmEstoque))
                                    .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldGerenciarProdutosPrecoDeCusto, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldGerenciarProdutosPreco, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jTextFieldGerenciarProdutosDescricao))))))))
                .addContainerGap())
        );
        jPanelGerenciarProdutosLayout.setVerticalGroup(
            jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jTextFieldGerenciarProdutosID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextFieldGerenciarProdutosNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextFieldGerenciarProdutosDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldGerenciarProdutosPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldGerenciarProdutosPrecoDeCusto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextFieldGerenciarProdutosQuantEmEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jPanelGerenciarProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonGerenciarProdutosExcluirProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButtonGerenciarProdutosAdicionarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonGerenciarProdutosAtualizarProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPaneGerenciar.addTab("Produtos", jPanelGerenciarProdutos);

        javax.swing.GroupLayout jPanelGerenciarLayout = new javax.swing.GroupLayout(jPanelGerenciar);
        jPanelGerenciar.setLayout(jPanelGerenciarLayout);
        jPanelGerenciarLayout.setHorizontalGroup(
            jPanelGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelGerenciarLayout.createSequentialGroup()
                .addComponent(jTabbedPaneGerenciar)
                .addContainerGap())
        );
        jPanelGerenciarLayout.setVerticalGroup(
            jPanelGerenciarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneGerenciar)
        );

        mainPanel.addTab("Gerenciar", jPanelGerenciar);

        jMenu1.setText("Caixa");

        jMenuAbrirCaixa.setText("Abrir caixa");
        jMenuAbrirCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAbrirCaixaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuAbrirCaixa);

        jMenuFecharCaixa.setText("Fechar caixa");
        jMenuFecharCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuFecharCaixaActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuFecharCaixa);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCaixaFecharComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaFecharComandaActionPerformed
        Double troco;
        do
        {
            String dinheiro = JOptionPane.showInputDialog(null, "Valor restante: "+String.valueOf(this.totalDaComanda) + "\n Didite o valor para pagar:", "Fechar comanda", JOptionPane.QUESTION_MESSAGE);
            if(Double.parseDouble(dinheiro) >= this.totalDaComanda)
            {
                troco = Double.parseDouble(dinheiro) - this.totalDaComanda;
                this.totalDaComanda = 0.0;
                JOptionPane.showMessageDialog(null, "O troco é de: R$" + String.valueOf(troco), "Troco", JOptionPane.INFORMATION_MESSAGE);
            }
            else
            {
                
                this.totalDaComanda = this.totalDaComanda - Double.parseDouble(dinheiro);
            }
        }
        while(this.totalDaComanda != 0.0);
        
        this.database.deleteOneDocument("comandas", "_id", this.jTextFieldCaixaIdComanda.getText());
        this.jTextFieldCaixaIdComanda.setText("");
        this.jTextFieldCaixaCPFDoCliente.setEnabled(false);
        this.jButtonCaixaAbrirComanda.setEnabled(false);
        this.jTextFieldCaixaViewNomeCliente.setText("");
        this.jTextFieldCaixaViewClienteCPF.setText("");
        this.jTextFieldCaixaViewTotalComanda.setText("");
        this.modelProdutosDaComanda.setRowCount(0);
        this.totalDaComanda = 0.0;
        this.jButtonCaixaFecharComanda.setEnabled(false);
        this.jTextFieldCaixaComandasAbertas.setText(String.valueOf(database.getNumComandas()));
        

    }//GEN-LAST:event_jButtonCaixaFecharComandaActionPerformed

    private void jButtonGerenciarClientesAddClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarClientesAddClienteActionPerformed
        Cliente cli = new Cliente(this.jTextFieldGerenciarClientesCPF.getText(),
                                  this.jTextFieldGerenciarClientesNome.getText(),
                                  this.jTextFieldGerenciarClientesSobrenome.getText(),
                                  this.jTextFieldGerenciarClientesEndereco.getText(),
                                  this.jTextFieldGerenciarClientesNascimento.getText(),
                                  this.jTextFieldGerenciarClientesTelefone.getText());
        this.database.createOneDocument("clientes", cli.getDocument());
        JOptionPane.showMessageDialog(null, "Cliente adicionado com sucesso", "Cliente adicionado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarClientesAddClienteActionPerformed

    private void jButtonGerenciarClientesAtualizarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarClientesAtualizarClienteActionPerformed
        Cliente cli = new Cliente(this.jTextFieldGerenciarClientesCPF.getText(),
                                  this.jTextFieldGerenciarClientesNome.getText(),
                                  this.jTextFieldGerenciarClientesSobrenome.getText(),
                                  this.jTextFieldGerenciarClientesEndereco.getText(),
                                  this.jTextFieldGerenciarClientesNascimento.getText(),
                                  this.jTextFieldGerenciarClientesTelefone.getText());
        this.database.updateOneDocument(cli.getCollectionName(), "_id", cli.getCpf(), cli.getDocument());
        JOptionPane.showMessageDialog(null, "Cliente atualizado com sucesso", "Cliente atualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarClientesAtualizarClienteActionPerformed

    private void jButtonGerenciarClientesExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarClientesExcluirClienteActionPerformed
        Cliente cli = new Cliente(this.jTextFieldGerenciarClientesCPF.getText(),
                                  this.jTextFieldGerenciarClientesNome.getText(),
                                  this.jTextFieldGerenciarClientesSobrenome.getText(),
                                  this.jTextFieldGerenciarClientesEndereco.getText(),
                                  this.jTextFieldGerenciarClientesNascimento.getText(),
                                  this.jTextFieldGerenciarClientesTelefone.getText());
        this.database.deleteOneDocument(cli.getCollectionName(), "_id", cli.getCpf());
        JOptionPane.showMessageDialog(null, "Cliente excluído com sucesso", "Cliente excluído", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarClientesExcluirClienteActionPerformed

    private void jButtonGerenciarProdutosAdicionarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarProdutosAdicionarProdutoActionPerformed
        Produto pro = new Produto(this.jTextFieldGerenciarProdutosID.getText(), 
                                  this.jTextFieldGerenciarProdutosNome.getText(), 
                                  this.jTextFieldGerenciarProdutosDescricao.getText(), 
                                  this.jTextFieldGerenciarProdutosPreco.getText(), 
                                  this.jTextFieldGerenciarProdutosPrecoDeCusto.getText(), 
                                  Integer.parseInt(this.jTextFieldGerenciarProdutosQuantEmEstoque.getText()));
        this.database.createOneDocument(pro.getCollectionName(), pro.getDocument());
        this.populaJTableProdutos();
        JOptionPane.showMessageDialog(null, "Produto adicionado com sucesso!", "Produto adicionado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarProdutosAdicionarProdutoActionPerformed

    private void jButtonGerenciarProdutosAtualizarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarProdutosAtualizarProdutoActionPerformed
        Produto pro = new Produto(this.jTextFieldGerenciarProdutosID.getText(), 
                                  this.jTextFieldGerenciarProdutosNome.getText(), 
                                  this.jTextFieldGerenciarProdutosDescricao.getText(), 
                                  this.jTextFieldGerenciarProdutosPreco.getText(), 
                                  this.jTextFieldGerenciarProdutosPrecoDeCusto.getText(), 
                                  Integer.parseInt(this.jTextFieldGerenciarProdutosQuantEmEstoque.getText()));
        this.database.updateOneDocument(pro.getCollectionName(), "_id", pro.getId(), pro.getDocument());
        this.populaJTableProdutos();
        JOptionPane.showMessageDialog(null, "Produto atualizado com sucesso!", "Produto atualizado", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarProdutosAtualizarProdutoActionPerformed

    private void jButtonGerenciarProdutosExcluirProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerenciarProdutosExcluirProdutoActionPerformed
        Produto pro = new Produto(this.jTextFieldGerenciarProdutosID.getText(), 
                                  this.jTextFieldGerenciarProdutosNome.getText(), 
                                  this.jTextFieldGerenciarProdutosDescricao.getText(), 
                                  this.jTextFieldGerenciarProdutosPreco.getText(), 
                                  this.jTextFieldGerenciarProdutosPrecoDeCusto.getText(), 
                                  Integer.parseInt(this.jTextFieldGerenciarProdutosQuantEmEstoque.getText()));
        this.database.deleteOneDocument(pro.getCollectionName(), "_id", pro.getId());
        this.populaJTableProdutos();
        JOptionPane.showMessageDialog(null, "Produto excluído com sucesso!", "Produto excluído.", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_jButtonGerenciarProdutosExcluirProdutoActionPerformed

    private void jButtonCaixaAbrirComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCaixaAbrirComandaActionPerformed
        boolean incluir = true;
        if(database.clienteTemComanda(this.jTextFieldCaixaCPFDoCliente.getText()))
        {
            int op = JOptionPane.showConfirmDialog(null, "O cliente já tem uma comanda aberta, tem certeza que deseja abrir outra?", "Comanda já aberta", JOptionPane.YES_NO_OPTION);
            if(op == JOptionPane.YES_OPTION){
            }
            else
                incluir = false;
        }
        
        if(incluir)
        {
            Comanda com = new Comanda(this.jTextFieldCaixaIdComanda.getText(), 
                                      database.getCliente(this.jTextFieldCaixaCPFDoCliente.getText()),
                                      new ArrayList<Produto>()
                                    );
            this.database.createOneDocument(com.getCollectionName(), com.getDocument());
            this.jTextFieldCaixaComandasAbertas.setText(String.valueOf(database.getNumComandas()));
            this.jTextFieldCaixaIdComanda.setText("");
            this.jTextFieldCaixaCPFDoCliente.setText("");
            this.jTextFieldCaixaCPFDoCliente.setEnabled(false);
            this.jButtonCaixaAbrirComanda.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Comanda aberta com sucesso!", "Comanda aberta", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_jButtonCaixaAbrirComandaActionPerformed

    private void jTextFieldCaixaIdComandaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCaixaIdComandaKeyReleased
        if(Verificador.verificaIdComanda(this.jTextFieldCaixaIdComanda.getText()))
        {
            Comanda comanda = this.database.getComanda(this.jTextFieldCaixaIdComanda.getText());
            if(comanda != null)
            {
                this.jTextFieldCaixaViewNomeCliente.setText(comanda.getCliente().getNome());
                this.jTextFieldCaixaViewClienteCPF.setText(comanda.getCliente().getCpf());
                ArrayList<Produto> produtosDaComanda = comanda.getProdutos();
                if(produtosDaComanda.isEmpty())
                    this.jTextFieldCaixaViewTotalComanda.setText("R$ 00,00");
                else
                {
                    double total = 0.0;
                    for(Iterator<Produto> i = produtosDaComanda.iterator(); i.hasNext();)
                    {
                        Produto pro = i.next();
                        Object[] row = {pro.getNome(), "R$: " + pro.getPreco()};
                        total += Double.parseDouble(pro.getPreco());
                        this.modelProdutosDaComanda.addRow(row);
                    }
                    this.totalDaComanda = total;
                    this.jTextFieldCaixaViewTotalComanda.setText("R$ " + String.valueOf(total));
                }
                this.jButtonCaixaFecharComanda.setEnabled(true);
            }
            else
            {
                this.jTextFieldCaixaCPFDoCliente.setEnabled(true);
                this.jButtonCaixaAbrirComanda.setEnabled(false);
                this.jTextFieldCaixaViewNomeCliente.setText("");
                this.jTextFieldCaixaViewClienteCPF.setText("");
                this.jTextFieldCaixaViewTotalComanda.setText("");
                this.modelProdutosDaComanda.setRowCount(0);
                this.totalDaComanda = 0.0;
                this.jButtonCaixaFecharComanda.setEnabled(false);
            }
        }
        else
        {
            this.jTextFieldCaixaCPFDoCliente.setEnabled(false);
            this.jButtonCaixaAbrirComanda.setEnabled(false);
            this.jTextFieldCaixaViewNomeCliente.setText("");
            this.jTextFieldCaixaViewClienteCPF.setText("");
            this.jTextFieldCaixaViewTotalComanda.setText("");
            this.modelProdutosDaComanda.setRowCount(0);
            this.totalDaComanda = 0.0;
            this.jButtonCaixaFecharComanda.setEnabled(false);
        }
            
    }//GEN-LAST:event_jTextFieldCaixaIdComandaKeyReleased

    private void jMenuAbrirCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAbrirCaixaActionPerformed
        try{
            this.database.updateOneDocument(this.caixa.getCollectionName(), "_id", this.caixa.getId(), this.caixa.abrirCaixa());
            this.jTextFieldCaixaEstado.setText(this.caixa.caixaAberto()? "ABERTO" : "FECHADO");
            this.jTextFieldCaixaIdComanda.setEnabled(true);
        }catch(CaixaAbertoException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuAbrirCaixaActionPerformed

    private void jMenuFecharCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuFecharCaixaActionPerformed
        try{
            this.database.updateOneDocument(this.caixa.getCollectionName(), "_id", this.caixa.getId(), this.caixa.fecharCaixa());
            this.jTextFieldCaixaEstado.setText(this.caixa.caixaAberto()? "ABERTO" : "FECHADO");
            this.jTextFieldCaixaIdComanda.setEnabled(false);
        }catch(CaixaFechadoException e){
            JOptionPane.showMessageDialog(null, e.getMessage(), "Erro", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jMenuFecharCaixaActionPerformed

    private void jTextFieldServicoIdDaComandaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldServicoIdDaComandaKeyReleased
        if(Verificador.verificaIdComanda(this.jTextFieldServicoIdDaComanda.getText()))
        {
            Comanda comanda = this.database.getComanda(this.jTextFieldServicoIdDaComanda.getText());
            if(comanda != null)
            {
                this.jButtonInserirNaComanda.setEnabled(true);
                this.jTextFieldServicoViewNomeCliente.setText(comanda.getCliente().getNome());
                this.jTextFieldServicoViewClienteCPF.setText(comanda.getCliente().getCpf());
                ArrayList<Produto> produtosDaComanda = comanda.getProdutos();
                if(produtosDaComanda.isEmpty())
                    this.jTextFieldServicoViewTotalComanda.setText("R$ 00,00");
                else
                {
                    this.modelServicoProdutosDaComanda.setRowCount(0);
                    double total = 0.0;
                    for(Iterator<Produto> i = produtosDaComanda.iterator(); i.hasNext();)
                    {
                        Produto pro = i.next();
                        Object[] row = {pro.getNome(), "R$: " + pro.getPreco()};
                        total += Double.parseDouble(pro.getPreco());
                        this.modelServicoProdutosDaComanda.addRow(row);
                    }
                    this.jTextFieldServicoViewTotalComanda.setText("R$ " + String.valueOf(total));
                }
            }
            else
            {
                this.jButtonInserirNaComanda.setEnabled(false);
                this.jTextFieldServicoViewNomeCliente.setText("");
                this.jTextFieldServicoViewClienteCPF.setText("");
                this.jTextFieldServicoViewTotalComanda.setText("");
                this.modelServicoProdutosDaComanda.setRowCount(0);
            }
        }
        else
        {
            this.jButtonInserirNaComanda.setEnabled(false);
            this.jTextFieldServicoViewNomeCliente.setText("");
            this.jTextFieldServicoViewClienteCPF.setText("");
            this.jTextFieldServicoViewTotalComanda.setText("");
            this.modelServicoProdutosDaComanda.setRowCount(0);
        }
    }//GEN-LAST:event_jTextFieldServicoIdDaComandaKeyReleased

    private void jButtonInserirNaComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInserirNaComandaActionPerformed
        if(this.jTableServicoProdutos.getSelectedRow() > -1)
        {
            Comanda comanda = this.database.getComanda(this.jTextFieldServicoIdDaComanda.getText());
            Produto pro = this.database.getProduto(this.modelProdutos.getValueAt(this.jTableServicoProdutos.getSelectedRow(), 0).toString());
            comanda.addProduto(pro);
            this.database.updateOneDocument("comandas", "_id", comanda.getId(), comanda.getDocument());
            // atualizar jtable
            
            ArrayList<Produto> produtosDaComanda = comanda.getProdutos();
            this.modelServicoProdutosDaComanda.setRowCount(0);
            double total = 0.0;
            for (Iterator<Produto> i = produtosDaComanda.iterator(); i.hasNext();) {
                Produto aux = i.next();
                Object[] row = {aux.getNome(), "R$: " + aux.getPreco()};
                this.modelServicoProdutosDaComanda.addRow(row);
                total += Double.parseDouble(pro.getPreco());
            }
            total += Double.parseDouble(pro.getPreco());
            this.jTextFieldServicoViewTotalComanda.setText("R$ " + String.valueOf(total));
            JOptionPane.showMessageDialog(null, "Produto inserido com sucesso!", "Produto inserido", JOptionPane.INFORMATION_MESSAGE);
            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Selecione um produto antes de adicionar.", "Selecione um produto", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonInserirNaComandaActionPerformed

    private void jTextFieldCaixaIdComandaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCaixaIdComandaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCaixaIdComandaActionPerformed

    private void jTextFieldCaixaCPFDoClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCaixaCPFDoClienteKeyReleased
        if(Verificador.verificaCpf(this.jTextFieldCaixaCPFDoCliente.getText()))
        {
            if(this.database.getCliente(this.jTextFieldCaixaCPFDoCliente.getText()) != null) // existe o cliente
                this.jButtonCaixaAbrirComanda.setEnabled(true);
            else
                this.jButtonCaixaAbrirComanda.setEnabled(false);
        }
        else
            this.jButtonCaixaAbrirComanda.setEnabled(false);
    }//GEN-LAST:event_jTextFieldCaixaCPFDoClienteKeyReleased

    private void jTextFieldGerenciarClientesCPFKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGerenciarClientesCPFKeyReleased
        if(Verificador.verificaCpf(this.jTextFieldGerenciarClientesCPF.getText()))
        {
            Cliente cliente = database.getCliente(this.jTextFieldGerenciarClientesCPF.getText());
            if(cliente != null)
            {
                // se o cliente existe
                this.jTextFieldGerenciarClientesNome.setText(cliente.getNome());
                this.jTextFieldGerenciarClientesSobrenome.setText(cliente.getSobrenome());
                this.jTextFieldGerenciarClientesNascimento.setText(cliente.getNascimento());
                this.jTextFieldGerenciarClientesEndereco.setText(cliente.getEndereco());
                this.jTextFieldGerenciarClientesTelefone.setText(cliente.getTelefone());
                this.jButtonGerenciarClientesAtualizarCliente.setEnabled(true);
                this.jButtonGerenciarClientesExcluirCliente.setEnabled(true);
                this.jButtonGerenciarClientesAddCliente.setEnabled(false);
            }
            else
            {
                this.jButtonGerenciarClientesAddCliente.setEnabled(true);
                this.jButtonGerenciarClientesAtualizarCliente.setEnabled(false);
                this.jButtonGerenciarClientesExcluirCliente.setEnabled(false);
            }
        }
        else
        {
            this.jButtonGerenciarClientesAtualizarCliente.setEnabled(false);
            this.jButtonGerenciarClientesExcluirCliente.setEnabled(false);
            this.jButtonGerenciarClientesAddCliente.setEnabled(false);
            
            this.jTextFieldGerenciarClientesNome.setText("");
            this.jTextFieldGerenciarClientesSobrenome.setText("");
            this.jTextFieldGerenciarClientesNascimento.setText("");
            this.jTextFieldGerenciarClientesEndereco.setText("");
            this.jTextFieldGerenciarClientesTelefone.setText("");
        }
    }//GEN-LAST:event_jTextFieldGerenciarClientesCPFKeyReleased

    private void jTextFieldGerenciarProdutosIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldGerenciarProdutosIDKeyReleased
        if(Verificador.verificaIdProduto(this.jTextFieldGerenciarProdutosID.getText()))
        {
            Produto produto = database.getProduto(this.jTextFieldGerenciarProdutosID.getText());
            if(produto != null)
            {
                this.jTextFieldGerenciarProdutosNome.setText(produto.getNome());
                this.jTextFieldGerenciarProdutosPreco.setText(produto.getPreco());
                this.jTextFieldGerenciarProdutosPrecoDeCusto.setText(produto.getPrecoDeCusto());
                this.jTextFieldGerenciarProdutosQuantEmEstoque.setText(String.valueOf(produto.getQuantEmEstoque()));
                this.jTextFieldGerenciarProdutosDescricao.setText(produto.getDescricao());
                
                this.jButtonGerenciarProdutosAtualizarProduto.setEnabled(true);
                this.jButtonGerenciarProdutosExcluirProduto.setEnabled(true);
                this.jButtonGerenciarProdutosAdicionarProduto.setEnabled(false);
            }
            else
            {
                this.jButtonGerenciarProdutosAdicionarProduto.setEnabled(true);
                this.jButtonGerenciarProdutosAtualizarProduto.setEnabled(false);
            this.jButtonGerenciarProdutosExcluirProduto.setEnabled(false);
            }
        }
        else
        {
            this.jButtonGerenciarProdutosAtualizarProduto.setEnabled(false);
            this.jButtonGerenciarProdutosExcluirProduto.setEnabled(false);
            this.jButtonGerenciarProdutosAdicionarProduto.setEnabled(false);
            
            this.jTextFieldGerenciarProdutosNome.setText("");
            this.jTextFieldGerenciarProdutosPreco.setText("");
            this.jTextFieldGerenciarProdutosPrecoDeCusto.setText("");
            this.jTextFieldGerenciarProdutosQuantEmEstoque.setText("");
            this.jTextFieldGerenciarProdutosDescricao.setText("");
        }
    }//GEN-LAST:event_jTextFieldGerenciarProdutosIDKeyReleased

    private void jTextFieldGerenciarClientesNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGerenciarClientesNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGerenciarClientesNascimentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewController.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewController().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCaixaAbrirComanda;
    private javax.swing.JButton jButtonCaixaFecharComanda;
    private javax.swing.JButton jButtonGerenciarClientesAddCliente;
    private javax.swing.JButton jButtonGerenciarClientesAtualizarCliente;
    private javax.swing.JButton jButtonGerenciarClientesExcluirCliente;
    private javax.swing.JButton jButtonGerenciarProdutosAdicionarProduto;
    private javax.swing.JButton jButtonGerenciarProdutosAtualizarProduto;
    private javax.swing.JButton jButtonGerenciarProdutosExcluirProduto;
    private javax.swing.JButton jButtonInserirNaComanda;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCaixaCPF;
    private javax.swing.JLabel jLabelCaixaCPF1;
    private javax.swing.JLabel jLabelCaixaCliente;
    private javax.swing.JLabel jLabelCaixaCliente1;
    private javax.swing.JLabel jLabelCaixaComandasAbertas;
    private javax.swing.JLabel jLabelCaixaEstado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAbrirCaixa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuFecharCaixa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelCaixa;
    private javax.swing.JPanel jPanelGerenciar;
    private javax.swing.JPanel jPanelGerenciarClientes;
    private javax.swing.JPanel jPanelGerenciarProdutos;
    private javax.swing.JPanel jPanelServico;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparatorCaixaCabeçalho;
    private javax.swing.JTabbedPane jTabbedPaneGerenciar;
    private javax.swing.JTable jTableCaixaComanda;
    private javax.swing.JTable jTableServicoProdutos;
    private javax.swing.JTable jTableServicoProdutosDaComanda;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCaixaCPFDoCliente;
    private javax.swing.JTextField jTextFieldCaixaComandasAbertas;
    private javax.swing.JTextField jTextFieldCaixaEstado;
    private javax.swing.JTextField jTextFieldCaixaIdComanda;
    private javax.swing.JTextField jTextFieldCaixaViewClienteCPF;
    private javax.swing.JTextField jTextFieldCaixaViewNomeCliente;
    private javax.swing.JTextField jTextFieldCaixaViewTotalComanda;
    private javax.swing.JTextField jTextFieldGerenciarClientesCPF;
    private javax.swing.JTextField jTextFieldGerenciarClientesEndereco;
    private javax.swing.JTextField jTextFieldGerenciarClientesNascimento;
    private javax.swing.JTextField jTextFieldGerenciarClientesNome;
    private javax.swing.JTextField jTextFieldGerenciarClientesSobrenome;
    private javax.swing.JTextField jTextFieldGerenciarClientesTelefone;
    private javax.swing.JTextField jTextFieldGerenciarProdutosDescricao;
    private javax.swing.JTextField jTextFieldGerenciarProdutosID;
    private javax.swing.JTextField jTextFieldGerenciarProdutosNome;
    private javax.swing.JTextField jTextFieldGerenciarProdutosPreco;
    private javax.swing.JTextField jTextFieldGerenciarProdutosPrecoDeCusto;
    private javax.swing.JTextField jTextFieldGerenciarProdutosQuantEmEstoque;
    private javax.swing.JTextField jTextFieldServicoIdDaComanda;
    private javax.swing.JTextField jTextFieldServicoViewClienteCPF;
    private javax.swing.JTextField jTextFieldServicoViewNomeCliente;
    private javax.swing.JTextField jTextFieldServicoViewTotalComanda;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTabbedPane mainPanel;
    // End of variables declaration//GEN-END:variables
}
